/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.JToggleButton;

/**
 *
 * @author frealgagu
 */
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
         setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegistrarseDialog = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tarjetaCrédito = new javax.swing.JButton();
        cuentaAhorros = new javax.swing.JButton();
        nombreNuevo = new javax.swing.JTextField();
        idNuevo = new javax.swing.JTextField();
        cambiarMensajeSaldo = new javax.swing.JLabel();
        cupoSaldo = new javax.swing.JTextField();
        listo = new javax.swing.JButton();
        OpcionesUsuario = new javax.swing.JDialog();
        verSaldo = new javax.swing.JButton();
        consignarCuenta = new javax.swing.JButton();
        retirarCuenta = new javax.swing.JButton();
        crearCuenta = new javax.swing.JButton();
        tarjetaCreditoOpcion = new javax.swing.JRadioButton();
        cuentaAhorrosOpcion = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        respuestaCuentas = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        registrarse = new javax.swing.JToggleButton();
        accederalSistema = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ultimosMovimientos = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();

        RegistrarseDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Digite su nombre:");

        jLabel2.setText("Digite su ID:");

        jLabel3.setText("¿Qué cuenta desea crear en primera instancia?");

        tarjetaCrédito.setText("Tarjeta Crédito");
        tarjetaCrédito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarjetaCréditoActionPerformed(evt);
            }
        });

        cuentaAhorros.setText("Ahorros");

        cupoSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cupoSaldoActionPerformed(evt);
            }
        });

        listo.setText("Listo");

        javax.swing.GroupLayout RegistrarseDialogLayout = new javax.swing.GroupLayout(RegistrarseDialog.getContentPane());
        RegistrarseDialog.getContentPane().setLayout(RegistrarseDialogLayout);
        RegistrarseDialogLayout.setHorizontalGroup(
            RegistrarseDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistrarseDialogLayout.createSequentialGroup()
                .addGroup(RegistrarseDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistrarseDialogLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(tarjetaCrédito))
                    .addGroup(RegistrarseDialogLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(cuentaAhorros)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(RegistrarseDialogLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(RegistrarseDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistrarseDialogLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(RegistrarseDialogLayout.createSequentialGroup()
                        .addGroup(RegistrarseDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(57, 57, 57)
                        .addGroup(RegistrarseDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreNuevo)
                            .addComponent(idNuevo))))
                .addGap(29, 29, 29))
            .addGroup(RegistrarseDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RegistrarseDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(listo)
                    .addComponent(cambiarMensajeSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(cupoSaldo))
        );
        RegistrarseDialogLayout.setVerticalGroup(
            RegistrarseDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistrarseDialogLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(RegistrarseDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombreNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(RegistrarseDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(idNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(tarjetaCrédito)
                .addGap(18, 18, 18)
                .addComponent(cuentaAhorros)
                .addGap(26, 26, 26)
                .addGroup(RegistrarseDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cambiarMensajeSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cupoSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        OpcionesUsuario.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        OpcionesUsuario.setTitle("¿Qué opción desea?");

        verSaldo.setText("Ver saldo");
        verSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verSaldoActionPerformed(evt);
            }
        });

        consignarCuenta.setText("Consignar cuenta");
        consignarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consignarCuentaActionPerformed(evt);
            }
        });

        retirarCuenta.setText("Retirar Cuenta");
        retirarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retirarCuentaActionPerformed(evt);
            }
        });

        crearCuenta.setText("Crear cuenta");
        crearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearCuentaActionPerformed(evt);
            }
        });

        buttonGroup1.add(tarjetaCreditoOpcion);
        tarjetaCreditoOpcion.setText("Tarjeta de Crédito");
        tarjetaCreditoOpcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarjetaCreditoOpcionActionPerformed(evt);
            }
        });

        buttonGroup1.add(cuentaAhorrosOpcion);
        cuentaAhorrosOpcion.setText("Cuenta de ahorros");
        cuentaAhorrosOpcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuentaAhorrosOpcionActionPerformed(evt);
            }
        });

        jLabel4.setText("Escoja con qué tipo de cuenta desea hacer la acción");

        jLabel6.setText("Escoja qué acción desea hacer");

        respuestaCuentas.setEditable(false);
        respuestaCuentas.setColumns(20);
        respuestaCuentas.setRows(5);
        jScrollPane2.setViewportView(respuestaCuentas);

        jLabel7.setText("Respuesta:");

        javax.swing.GroupLayout OpcionesUsuarioLayout = new javax.swing.GroupLayout(OpcionesUsuario.getContentPane());
        OpcionesUsuario.getContentPane().setLayout(OpcionesUsuarioLayout);
        OpcionesUsuarioLayout.setHorizontalGroup(
            OpcionesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OpcionesUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OpcionesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OpcionesUsuarioLayout.createSequentialGroup()
                        .addComponent(consignarCuenta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(crearCuenta)
                        .addGap(48, 48, 48))
                    .addGroup(OpcionesUsuarioLayout.createSequentialGroup()
                        .addGroup(OpcionesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tarjetaCreditoOpcion)
                            .addComponent(jLabel4)
                            .addComponent(cuentaAhorrosOpcion)
                            .addComponent(jLabel6))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OpcionesUsuarioLayout.createSequentialGroup()
                        .addComponent(verSaldo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(retirarCuenta)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OpcionesUsuarioLayout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())))
            .addGroup(OpcionesUsuarioLayout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jLabel7)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        OpcionesUsuarioLayout.setVerticalGroup(
            OpcionesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OpcionesUsuarioLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(tarjetaCreditoOpcion)
                .addGap(18, 18, 18)
                .addComponent(cuentaAhorrosOpcion)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(OpcionesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verSaldo)
                    .addComponent(retirarCuenta))
                .addGap(29, 29, 29)
                .addGroup(OpcionesUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consignarCuenta)
                    .addComponent(crearCuenta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Opciones Banco");

        registrarse.setText("Registrarse");
        registrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarseActionPerformed(evt);
            }
        });

        accederalSistema.setText("Acceder al sistema");

        ultimosMovimientos.setEditable(false);
        ultimosMovimientos.setColumns(20);
        ultimosMovimientos.setRows(5);
        jScrollPane1.setViewportView(ultimosMovimientos);

        jLabel5.setText("Últimos movimientos:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(registrarse))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(accederalSistema))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel5)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(registrarse)
                .addGap(29, 29, 29)
                .addComponent(accederalSistema)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrarseActionPerformed

    private void tarjetaCréditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarjetaCréditoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tarjetaCréditoActionPerformed

    private void tarjetaCreditoOpcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarjetaCreditoOpcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tarjetaCreditoOpcionActionPerformed

    private void cuentaAhorrosOpcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuentaAhorrosOpcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuentaAhorrosOpcionActionPerformed

    private void crearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crearCuentaActionPerformed

    private void cupoSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cupoSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cupoSaldoActionPerformed

    private void consignarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consignarCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consignarCuentaActionPerformed

    private void verSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verSaldoActionPerformed

    private void retirarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retirarCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_retirarCuentaActionPerformed

    public JTextArea getRespuestaCuentas() {
        return respuestaCuentas;
    }

    public void setRespuestaCuentas(JTextArea respuestaCuentas) {
        this.respuestaCuentas = respuestaCuentas;
    }
    
    public void mostrarResultado(String m) {
        JOptionPane.showMessageDialog(null, m);
    }
    
    public int solicitarEntero(String m) {
        do {
            try {
                return Integer.parseInt(JOptionPane.showInputDialog(m));
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "El ID tiene que ser numérico");
            }
        } while(true);
    }
    
    public long solicitarLong(String m) {
        do {
            try {
                return Long.parseLong(JOptionPane.showInputDialog(m));
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "El ID tiene que ser numérico");
            }
        } while(true);
    }
    
    public JLabel getCambiarMensajeSaldo() {
        return cambiarMensajeSaldo;
    }

    public void setCambiarMensajeSaldo(JLabel cambiarMensajeSaldo) {
        this.cambiarMensajeSaldo = cambiarMensajeSaldo;
    }

    public JTextField getCupoSaldo() {
        return cupoSaldo;
    }

    public void setCupoSaldo(JTextField cupoSaldo) {
        this.cupoSaldo = cupoSaldo;
    }

    public JButton getListo() {
        return listo;
    }

    public void setListo(JButton listo) {
        this.listo = listo;
    }
    
    public JDialog getOpcionesUsuario() {
        return OpcionesUsuario;
    }

    public void setOpcionesUsuario(JDialog OpcionesUsuario) {
        this.OpcionesUsuario = OpcionesUsuario;
    }

    public JDialog getRegistrarseDialog() {
        return RegistrarseDialog;
    }

    public void setRegistrarseDialog(JDialog RegistrarseDialog) {
        this.RegistrarseDialog = RegistrarseDialog;
    }

    public JToggleButton getAccederalSistema() {
        return accederalSistema;
    }

    public void setAccederalSistema(JToggleButton accederalSistema) {
        this.accederalSistema = accederalSistema;
    }

    public JButton getConsignarCuenta() {
        return consignarCuenta;
    }

    public void setConsignarCuenta(JButton consignarCuenta) {
        this.consignarCuenta = consignarCuenta;
    }

    public JButton getCrearCuenta() {
        return crearCuenta;
    }

    public void setCrearCuenta(JButton crearCuenta) {
        this.crearCuenta = crearCuenta;
    }

    public JButton getCuentaAhorros() {
        return cuentaAhorros;
    }

    public void setCuentaAhorros(JButton cuentaAhorros) {
        this.cuentaAhorros = cuentaAhorros;
    }

    public JRadioButton getCuentaAhorrosOpcion() {
        return cuentaAhorrosOpcion;
    }

    public void setCuentaAhorrosOpcion(JRadioButton cuentaAhorrosOpcion) {
        this.cuentaAhorrosOpcion = cuentaAhorrosOpcion;
    }

    public JTextField getIdNuevo() {
        return idNuevo;
    }

    public void setIdNuevo(JTextField idNuevo) {
        this.idNuevo = idNuevo;
    }

    public JTextField getNombreNuevo() {
        return nombreNuevo;
    }

    public void setNombreNuevo(JTextField nombreNuevo) {
        this.nombreNuevo = nombreNuevo;
    }

    public JToggleButton getRegistrarse() {
        return registrarse;
    }

    public void setRegistrarse(JToggleButton registrarse) {
        this.registrarse = registrarse;
    }

    public JButton getRetirarCuenta() {
        return retirarCuenta;
    }

    public void setRetirarCuenta(JButton retirarCuenta) {
        this.retirarCuenta = retirarCuenta;
    }

    public JRadioButton getTarjetaCreditoOpcion() {
        return tarjetaCreditoOpcion;
    }

    public void setTarjetaCreditoOpcion(JRadioButton tarjetaCreditoOpcion) {
        this.tarjetaCreditoOpcion = tarjetaCreditoOpcion;
    }

    public JButton getTarjetaCrédito() {
        return tarjetaCrédito;
    }

    public void setTarjetaCrédito(JButton tarjetaCrédito) {
        this.tarjetaCrédito = tarjetaCrédito;
    }

    public JTextArea getUltimosMovimientos() {
        return ultimosMovimientos;
    }

    public void setUltimosMovimientos(JTextArea ultimosMovimientos) {
        this.ultimosMovimientos = ultimosMovimientos;
    }

    public JButton getVerSaldo() {
        return verSaldo;
    }

    public void setVerSaldo(JButton verSaldo) {
        this.verSaldo = verSaldo;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog OpcionesUsuario;
    private javax.swing.JDialog RegistrarseDialog;
    private javax.swing.JToggleButton accederalSistema;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel cambiarMensajeSaldo;
    private javax.swing.JButton consignarCuenta;
    private javax.swing.JButton crearCuenta;
    private javax.swing.JButton cuentaAhorros;
    private javax.swing.JRadioButton cuentaAhorrosOpcion;
    private javax.swing.JTextField cupoSaldo;
    private javax.swing.JTextField idNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton listo;
    private javax.swing.JTextField nombreNuevo;
    private javax.swing.JToggleButton registrarse;
    private javax.swing.JTextArea respuestaCuentas;
    private javax.swing.JButton retirarCuenta;
    private javax.swing.JRadioButton tarjetaCreditoOpcion;
    private javax.swing.JButton tarjetaCrédito;
    private javax.swing.JTextArea ultimosMovimientos;
    private javax.swing.JButton verSaldo;
    // End of variables declaration//GEN-END:variables
}
